/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./grammar.macro.js#53ea92b9185d86a92b290d5a79760ace1146b8ef
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
var _functionMixin;
let _initProto, _IdentifierDecs, _ListDecs, _KeywordDecs, _LiteralDecs, _PunctuatorDecs, _AnyDecs, _AllDecs, _OptionalDecs;
import { spam as m } from '@bablr/boot';
import { Node, InjectFrom, AllowEmpty, CoveredBy } from '@bablr/helpers/decorators';
import { eat, eatMatch, o, holdForMatch, fail } from '@bablr/helpers/grammar';
import { triviaEnhancer } from '@bablr/helpers/trivia';
import * as productions from '@bablr/helpers/productions';
import * as Comment from '@bablr/language-en-c-comments';
import { mixin as functionMixin } from './mixins/function.js';
import { mixin as jsonMixin } from './mixins/json.js';
import { mixin as statementMixin } from './mixins/statement.js';
import { mixin as logicMixin } from './mixins/logic.js';
import * as Regex from './regex.js';
export const type = Symbol.for('@bablr/language');
export const dependencies = {
  Regex,
  Comment
};
export const canonicalURL = 'https://bablr.org/languages/universe/es3';
let reservedWords = new Set(['abstract', 'arguments', 'boolean', 'break', 'byte', 'case', 'catch', 'char', 'continue', 'debugger', 'default', 'delete', 'do', 'double', 'else', 'eval', 'false', 'final', 'finally', 'float', 'for', 'function', 'goto', 'if', 'implements', 'in', 'instanceof', 'int', 'interface', 'long', 'native', 'new', 'null', 'package', 'private', 'protected', 'public', 'return', 'short', 'static', 'switch', 'synchronized', 'this', 'throw', 'throws', 'transient', 'true', 'try', 'typeof', 'var', 'void', 'volatile', 'while', 'with', 'yield']);
export const atrivialGrammar = class ES3Grammar extends (_functionMixin = functionMixin(jsonMixin(statementMixin(logicMixin(Object))))) {
  static {
    [_initProto] = _applyDecs(this, [[[AllowEmpty, Node], 2, "Program"], [_IdentifierDecs, 2, "Identifier"], [_ListDecs, 2, "List"], [_KeywordDecs, 2, "Keyword"], [_LiteralDecs, 2, "Literal"], [_PunctuatorDecs, 2, "Punctuator"], [_AnyDecs, 2, "Any"], [_AllDecs, 2, "All"], [_OptionalDecs, 2, "Optional"]], [], 0, void 0, _functionMixin).e;
  }
  constructor(...args) {
    super(...args);
    _initProto(this);
  }
  *[(_IdentifierDecs = [CoveredBy('Expression'), Node], _ListDecs = [AllowEmpty, InjectFrom(productions)], _KeywordDecs = [Node, InjectFrom(productions)], _LiteralDecs = [Node, InjectFrom(productions)], _PunctuatorDecs = [Node, InjectFrom(productions)], _AnyDecs = InjectFrom(productions), _AllDecs = InjectFrom(productions), _OptionalDecs = [AllowEmpty, InjectFrom(productions)], Symbol.for('@bablr/fragment'))]({
    props: {
      rootMatcher
    }
  }) {
    // needed for the trivia plugin
    yield eat(rootMatcher);
  }
  *Program() {
    yield eat(m`body[]: <_StatementList />`);
  }
  *Expression({
    props: {
      power = 34
    },
    s
  }) {
    let res;
    if (!s.holding) {
      if (res = yield eatMatch(m`<_JSONExpression />`)) {} else if (power >= 4 && (res = yield eatMatch(m`<UnaryExpression /typeof|\+\+|--|\+|-|void|delete|!/ />`))) {} else if (power >= 4 && (res = yield eatMatch(m`<NewExpression 'new' />`, o({
        power
      })))) {} else if (res = yield eatMatch(m`<Identifier />`)) {}
    } else {
      res = yield eatMatch(m`<_LogicExpression />`, o({
        power
      }));
    }
    if (res) {
      return holdForMatch(m`<__Expression />`, o({
        power
      }));
    }
  }
  *Identifier({
    ctx
  }) {
    let id = ctx.sourceTextFor(yield eat(m`value: <*Literal /[a-zA-Z_$][a-zA-Z\d_$]*/ />`));
    if (reservedWords.has(id)) yield fail();
  }
  *List() {}
  *Keyword() {}
  *Literal() {}
  *Punctuator() {}
  *Any() {}
  *All() {}
  *Optional() {}
};
export const grammar = triviaEnhancer({
  triviaIsAllowed: s => s.span === 'Bare',
  triviaMatcher: m`#: <_Comment:Trivia /[ \n\r\t]|\/\/|\/\*/ />`
}, atrivialGrammar);