/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./function.macro.js#01d66c0645098a9b1116f3e3438b8a11d7984caa
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
import { spam as m } from '@bablr/boot';
import { bindAttribute, eat, eatMatch, o } from '@bablr/helpers/grammar';
import { CoveredBy, Node, UnboundAttributes } from '@bablr/helpers/decorators';
export const mixin = Base => {
  let _initProto, _CallExpressionDecs, _NewExpressionDecs;
  return class ES3FunctionGrammar extends Base {
    static {
      [_initProto] = _applyDecs(this, [[Node, 2, "FunctionExpression"], [_CallExpressionDecs, 2, "CallExpression"], [_NewExpressionDecs, 2, "NewExpression"]], [], 0, void 0, Base).e;
    }
    constructor(...args) {
      super(...args);
      _initProto(this);
    }
    *[(_CallExpressionDecs = [UnboundAttributes(['power']), CoveredBy('Expression'), Node], _NewExpressionDecs = [UnboundAttributes(['power']), CoveredBy('Expression'), Node], "FunctionExpression")]() {
      yield eat(m`sigilToken: <*Keyword 'function' />`);
      yield eatMatch(m`id: <Identifier />`);
      yield eat(m`openParamsToken: <*Punctuator '(' { balanced: ')' } />`);
      yield eat(m`params[]: <List />`, o({
        element: m`<Identifier />`,
        allowTrailingSeparator: false,
        separator: m`separatorTokens[]: <*Punctuator ',' />`
      }));
      yield eat(m`closeParamsToken: <*Punctuator ')' { balancer: true } />`);
      yield eat(m`body: <BlockStatement />`);
    }
    *CallExpression() {
      yield bindAttribute('power', 6);
      yield eat(m`callee+$: <Expression />`, o({
        power: 4
      }));
      yield eat(m`openArgumentsToken: <*Punctuator '(' { balanced: ')' } />`);
      yield eat(m`arguments[]+: <List />`, o({
        element: m`<Identifier />`,
        allowTrailingSeparator: false,
        separator: m`separatorTokens[]: <*Punctuator ',' />`
      }));
      yield eat(m`closeArgumentsToken: <*Punctuator ')' { balancer: true } />`);
    }
    *NewExpression({
      value: props
    }) {
      const {
        power
      } = props?.value || {};
      yield eat(m`sigilToken: <*Keyword 'new' />`);
      yield eat(m`callee+$: <Expression />`, o({
        power: 4
      }));
      let p = yield power >= 4 ? eatMatch(m`openArgumentsToken: <*Punctuator '(' { balanced: ')' } />`) : eat(m`openArgumentsToken: <*Punctuator '(' { balanced: ')' } />`);
      if (p) {
        yield eat(m`arguments[]: <List />`, o({
          element: m`<Identifier />`,
          allowTrailingSeparator: false,
          separator: m`separatorTokens[]: <*Punctuator ',' />`
        }));
        yield eat(m`closeArgumentsToken: <*Punctuator ')' { balancer: true } />`);
        yield bindAttribute('power', 2);
      } else {
        yield eat(m`arguments[]: []`);
        yield eat(m`separatorTokens[]: []`);
        yield eat(m`closeArgumentsToken: null`);
        yield bindAttribute('power', 4);
      }
    }
  };
};