/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./json.macro.js#7146399539ec60b15dfcc36cb06433999b9bf210
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
import { re, spam as m } from '@bablr/boot';
import { eat, match, eatMatch, fail, o } from '@bablr/helpers/grammar';
import { Node, CoveredBy, AllowEmpty } from '@bablr/helpers/decorators';
import { buildString } from '@bablr/helpers/builders';
export const escapables = new Map(Object.entries({
  b: '\b',
  f: '\f',
  n: '\n',
  r: '\r',
  t: '\t',
  0: '\0',
  '\\': '\\',
  '/': '/'
}));
export const getCooked = (escapeNode, span, ctx) => {
  let cooked;
  const codeNode = escapeNode.get('code');
  const type = ctx.sourceTextFor(codeNode.get('typeToken'));
  const value = ctx.sourceTextFor(codeNode.get('value'));
  if (!span.startsWith('String:')) throw new Error();
  if (!type) {
    const match_ = ctx.sourceTextFor(codeNode);
    cooked = escapables.get(match_) || match_;
  } else if ('ux'.includes(type)) {
    cooked = parseInt(value, 16);
  } else {
    throw new Error();
  }
  return cooked.toString(10);
};
export const mixin = Base => {
  let _initProto, _BooleanDecs, _NullDecs, _ArrayDecs, _ObjectDecs, _StringDecs, _InfinityDecs, _NotANumberDecs, _NumberDecs;
  return class ES3JSONGrammar extends Base {
    static {
      [_initProto] = _applyDecs(this, [[_BooleanDecs, 2, "Boolean"], [_NullDecs, 2, "Null"], [_ArrayDecs, 2, "Array"], [_ObjectDecs, 2, "Object"], [Node, 2, "Property"], [_StringDecs, 2, "String"], [[AllowEmpty, Node], 2, "StringContent"], [Node, 2, "EscapeSequence"], [Node, 2, "EscapeCode"], [_InfinityDecs, 2, "Infinity"], [_NotANumberDecs, 2, "NotANumber"], [Node, 2, "UnsignedInteger"], [_NumberDecs, 2, "Number"]], [], 0, void 0, Base).e;
    }
    constructor(...args) {
      super(...args);
      _initProto(this);
    }
    *[(_BooleanDecs = [CoveredBy('JSONExpression'), CoveredBy('Expression'), Node], _NullDecs = [CoveredBy('JSONExpression'), CoveredBy('Expression'), Node], _ArrayDecs = [CoveredBy('JSONExpression'), CoveredBy('Expression'), Node], _ObjectDecs = [CoveredBy('JSONExpression'), CoveredBy('Expression'), Node], _StringDecs = [CoveredBy('JSONExpression'), CoveredBy('Expression'), Node], _InfinityDecs = [CoveredBy('JSONExpression'), CoveredBy('Expression'), Node], _NotANumberDecs = [CoveredBy('JSONExpression'), CoveredBy('Expression'), Node], _NumberDecs = [CoveredBy('JSONExpression'), CoveredBy('Expression'), Node], "JSONExpression")]() {
      yield eat(m`<_Any />`, [m`<Boolean /true|false/ />`, m`<Null 'null' />`, m`<Array '[' />`, m`<Object '{' />`, m`<String /['"]/ />`, m`<Number /\d/ />`, m`<Infinity 'Infinity' />`, m`<NotANumber 'NaN' />`]);
    }
    *Boolean() {
      yield eat(m`sigilToken: <*Keyword /true|false/ />`);
    }
    *Null() {
      yield eat(m`sigilToken: <*Keyword 'null' />`);
    }
    *Array() {
      yield eat(m`open: <*Punctuator '[' { balanced: ']' } />`);
      yield eat(m`elements[]+$: <_List />`, o({
        element: m`<__Expression />`,
        separator: m`separatorTokens[]: <*Punctuator ',' />`,
        allowTrailingSeparator: false
      }));
      yield eat(m`close: <*Punctuator ']' { balancer: true } />`);
    }
    *Object() {
      yield eat(m`open: <*Punctuator '{' { balanced: '}' } />`);
      yield eat(m`properties[]$: <_List />`, o({
        element: m`<Property />`,
        separator: m`separatorTokens[]: <*Punctuator ',' />`,
        allowTrailingSeparator: false
      }));
      yield eat(m`close: <*Punctuator '}' { balancer: true } />`);
    }
    *Property() {
      yield eat(m`key$: <Identifier />`);
      yield eat(m`mapOperator: <*Punctuator ':' />`);
      yield eat(m`value+$: <__Expression />`, o({
        power: 16
      }));
    }
    *String({
      ctx
    }) {
      let q = yield match(re`/['"]/`);
      if (!q) yield fail();
      const q_ = ctx.sourceTextFor(q);
      yield q_ === "'" ? eat(m`open: <*Punctuator "'" { balanced: "'", balancedSpan: 'String:Single' } />`) : eat(m`open: <*Punctuator '"' { balanced: '"', balancedSpan: 'String:Double' } />`);
      yield eat(m`content: <*StringContent />`);
      yield q_ === "'" ? eat(m`close: <*Punctuator "'" { balancer: true } />`) : eat(m`close: <*Punctuator '"' { balancer: true } />`);
    }
    *StringContent({
      state: {
        span
      }
    }) {
      let esc, lit;
      do {
        esc = (yield match('\\')) && (yield eat(m`@: <EscapeSequence />`));
        lit = span === 'String:Single' ? yield eatMatch(re`/[^\r\n\\']+/`) : yield eatMatch(re`/[^\r\n\\"]+/`);
      } while (esc || lit);
    }
    *EscapeSequence({
      state: {
        span
      },
      ctx
    }) {
      if (!span.startsWith('String')) {
        yield fail();
      }
      yield eat(m`escape: <*Punctuator '\\' { openSpan: 'Escape' } />`);
      let match;
      if (match = span === 'String:Single' ? yield match(re`/[\\/nrt0']/`) : yield match(re`/[\\/nrt0"]/`)) {
        const match_ = ctx.sourceTextFor(match);
        yield eat(m`code: <*Keyword ${buildString(match_)} { closeSpan: 'Escape' } />`);
      } else {
        yield eat(m`code: <EscapeCode { closeSpan: 'Escape' } />`);
      }
    }
    *EscapeCode() {
      if (yield match('x')) {
        yield eatMatch(m`typeToken: <*Keyword 'x' />`);
        yield eat(m`digits[]: <Digits /\d{2}/ />`);
        yield eat(m`close: null`);
      } else if (yield match('u')) {
        yield eatMatch(m`typeToken: <*Keyword 'u' />`);
        yield eat(m`digits[]: <Digits /\d{4}/ />`);
        yield eat(m`close: null`);
      } else {
        yield fail();
      }
    }
    *Infinity() {
      yield eat(m`sigilToken: <*Keyword 'Infinity' />`);
    }
    *NotANumber() {
      yield eat(m`sigilToken: <*Keyword 'NaN' />`);
    }
    *UnsignedInteger({
      props: {
        noDoubleZero = false
      },
      ctx
    }) {
      let firstDigit = ctx.sourceTextFor(yield eat(re`/\d/`));
      if (!noDoubleZero || firstDigit.value !== '0') {
        yield eatMatch(re`/\d+/`);
      }
    }
    *Number() {
      yield eat(m`wholePart$: <*UnsignedInteger />`, o({
        noDoubleZero: true
      }));
      let fs = yield eatMatch(m`fractionalSeparatorToken: <*Punctuator '.' />`, null, o({
        bind: true
      }));
      if (fs) {
        yield eat(m`fractionalPart$: <*UnsignedInteger />`);
      } else {
        yield eat(m`fractionalPart$: null`);
      }
      let es = yield eatMatch(m`exponentSeparatorToken: <*Punctuator /[eE]/ />`, null, o({
        bind: true
      }));
      if (es) {
        yield eat(m`exponentPart$: <Integer />`, {
          matchSign: /[+-]/
        });
      } else {
        yield eat(m`exponentPart$: null`);
      }
    }
  };
};