/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./variables.macro.js#aefccc587808e4a63b8c24b7f1d7935f654eef98
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
import { i } from '@bablr/boot';
import { Node } from '@bablr/helpers/decorators';
export const mixin = Base => {
  let _initProto;
  return class ES3VariablesGrammar extends Base {
    static {
      [_initProto] = _applyDecs(this, [[Node, 2, "Identifier"], [Node, 2, "VariableDeclaration"], [Node, 2, "VariableDeclarator"]], [], 0, void 0, Base).e;
    }
    constructor(...args) {
      super(...args);
      _initProto(this);
    }
    *Identifier() {
      yield i`eat(/[a-zA-Z_$][a-zA-Z\d_$]*/)`;
    }
    *VariableDeclaration() {
      yield i`eat(<*Keyword 'var' /> 'sigilToken')`;
      yield i`eat(<VariableDeclarator /> 'declarations[]')`;
      yield i`eat(<List /> 'declarations[]' {
      element: <VariableDeclarator />
      allowTrailingSeparator: false
      separator: <*Punctuator ',' />
    })`;
    }
    *VariableDeclarator() {
      yield i`eat(<*Identifier /> 'id')`;
      yield i`eat(<*Punctuator '=' /> 'sigilToken')`;
      yield i`eat(<*Statement /> 'init')`;
    }
  };
};